bump: cryptography update 39.0.2 -> 41.0.1
Signed-off-by: HanslettTheDev <HanslettTheDev@gmail.com>

restart actions

Signed-off-by: HanslettTheDev <HanslettTheDev@gmail.com>

bug: added a bug to find an existing issue

Signed-off-by: HanslettTheDev <HanslettTheDev@gmail.com>

undo-bug: removed the bug

Signed-off-by: HanslettTheDev <HanslettTheDev@gmail.com>

fix: updated the wsaa.py file

Signed-off-by: HanslettTheDev <HanslettTheDev@gmail.com>

refactor: used the sys module to check for the major version

Co-authored-by: Nico Sandoval <49107024+NicolasSandoval@users.noreply.github.com>

Only run release on original repository, not forks

This avoids errors with dependabot PR:
```
Run marvinpinto/action-automatic-releases@latest
Initializing the Automatic Releases action
Determining release tags
Retrieving commit history
Generating changelog
Generating release tag
  Attempting to create or update release tag "beta"
  Could not create new tag "refs/tags/beta" (Resource not accessible by integration) therefore updating existing tag "tags/beta"
  Error: Resource not accessible by integration
```

Signed-off-by: Nicolás Sandoval <nicolassandovalunm@gmail.com>

Properly fix dependabot read-only token

https://github.com/dependabot/dependabot-core/issues/3253
Signed-off-by: Nicolás Sandoval <nicolassandovalunm@gmail.com>

Bump future from 0.18.2 to 0.18.3

Bumps [future](https://github.com/PythonCharmers/python-future) from 0.18.2 to 0.18.3.
- [Release notes](https://github.com/PythonCharmers/python-future/releases)
- [Changelog](https://github.com/PythonCharmers/python-future/blob/master/docs/changelog.rst)
- [Commits](https://github.com/PythonCharmers/python-future/compare/v0.18.2...v0.18.3)

---
updated-dependencies:
- dependency-name: future
  dependency-type: direct:production
...

Signed-off-by: dependabot[bot] <support@github.com>
Signed-off-by: Nicolás Sandoval <nicolassandovalunm@gmail.com>

Cumulative updates f/ develop (python3 conversion)

* 2to3 -w file.py
* python -m black file.py
* iconv -f iso-8859-1 -t utf-8 < file_new.py > file.py

Signed-off-by: Nicolás Sandoval <nicolassandovalunm@gmail.com>

Update copyright and remove merge typo

Signed-off-by: Nicolás Sandoval <nicolassandovalunm@gmail.com>

WSFEv1: update copyright

Signed-off-by: Nicolás Sandoval <nicolassandovalunm@gmail.com>

WSFEv1: re-sync updates

Signed-off-by: Nicolás Sandoval <nicolassandovalunm@gmail.com>

WSFEXv1: disable get parameters until UT updated

Signed-off-by: Nicolás Sandoval <nicolassandovalunm@gmail.com>

Remove Python 2.7 deprecated GitHub Action

Signed-off-by: Nicolás Sandoval <nicolassandovalunm@gmail.com>

refactor: removed repeated code in signing certificates

Signed-off-by: HanslettTheDev <HanslettTheDev@gmail.com>